<Project Sdk="MSTest.Sdk/4.3.2">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <IsPackable>false</IsPackable>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\TimetableGenerator.CatalogJson\TimetableGenerator.CatalogJson.csproj" />
    <ProjectReference Include="..\..\src\TimetableGenerator.Domain\TimetableGenerator.Domain.csproj" />
    <ProjectReference Include="..\..\src\TimetableGenerator.Infrastructure\TimetableGenerator.Infrastructure.csproj" />
    <ProjectReference Include="..\..\tools\TimetableGenerator.HandongCatalogGenerator\TimetableGenerator.HandongCatalogGenerator.csproj" />
  </ItemGroup>
</Project>
